title: Pricelists
modelClass: LZaplata\Pricelists\Models\Pricelist
list: $/lzaplata/pricelists/models/pricelist/columns.yaml
recordUrl: 'lzaplata/pricelists/pricelists/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
